use crate::broker_error_messages::{
    CONFIG_LOAD_FAILED, COORDINATION_QUORUM_NOT_DISCOVERED, INVALID_BROKER_CONFIG, INVALID_BROKER_NODE_UUID,
    MESSAGE_TIMESTAMP_NOT_ADVANCING, PAYLOAD_SCHEMA_MISMATCH, TOPIC_ALREADY_EXISTS, UNKNOWN_TOPIC, WRITE_ADMISSION_REJECTED,
};
use crate::topic::{MessageNotification, MessagePayload, TimestampNs, TopicDefinition, TopicName};
use serde::Deserialize;
use std::{
    collections::HashMap,
    num::{NonZeroU16, NonZeroUsize},
    path::Path,
};
use thiserror::Error;
use tracing::{info, warn};
use uuid::Uuid;

/// Durable identity for a broker process.
///
/// IDs are generated by the broker instead of configured by operators so cluster
/// membership can be discovered and fenced by the coordination layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(transparent)]
pub struct BrokerNodeId(Uuid);

impl BrokerNodeId {
    pub fn generate() -> Self {
        Self(Uuid::new_v4())
    }

    pub fn new(value: Uuid) -> Self {
        Self(value)
    }

    pub fn parse(value: &str) -> Result<Self, BrokerError> {
        Uuid::parse_str(value)
            .map(Self)
            .map_err(|_| BrokerError::InvalidConfig(INVALID_BROKER_NODE_UUID))
    }

    pub fn as_uuid(&self) -> Uuid {
        self.0
    }
}

impl std::fmt::Display for BrokerNodeId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Operator-provided cluster size used to calculate quorum.
///
/// The configured count is deliberately separate from discovered membership:
/// every discovered broker is a voter, but writes are rejected until discovery
/// can prove that quorum is reachable.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ClusterConfig {
    expected_brokers: NonZeroUsize,
}

impl ClusterConfig {
    pub fn new(expected_brokers: NonZeroUsize) -> Self {
        Self { expected_brokers }
    }

    pub fn single_node() -> Self {
        Self::new(NonZeroUsize::MIN)
    }

    pub fn expected_brokers(&self) -> NonZeroUsize {
        self.expected_brokers
    }

    pub fn quorum_size(&self) -> NonZeroUsize {
        NonZeroUsize::new((self.expected_brokers.get() / 2) + 1).expect("majority quorum for non-zero cluster size is non-zero")
    }

    pub fn is_single_node(&self) -> bool {
        self.expected_brokers.get() == 1
    }
}

/// Inter-broker communication settings.
///
/// Only the local port is configured. Peer addresses are discovered dynamically
/// by the cluster coordination path, not hardcoded in configuration.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct InterBrokerConfig {
    port: NonZeroU16,
}

impl InterBrokerConfig {
    pub fn new(port: NonZeroU16) -> Self {
        Self { port }
    }

    pub fn port(&self) -> NonZeroU16 {
        self.port
    }
}

/// Static broker startup configuration loaded from TOML, JSON, or YAML.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct BrokerConfig {
    cluster: ClusterConfig,
    inter_broker: InterBrokerConfig,
}

impl BrokerConfig {
    pub fn new(cluster: ClusterConfig, inter_broker: InterBrokerConfig) -> Self {
        Self { cluster, inter_broker }
    }

    pub fn single_node(port: NonZeroU16) -> Self {
        Self::new(ClusterConfig::single_node(), InterBrokerConfig::new(port))
    }

    pub fn from_path(path: impl AsRef<Path>) -> Result<Self, BrokerError> {
        config::Config::builder()
            .add_source(config::File::from(path.as_ref()))
            .build()
            .map_err(|_| BrokerError::ConfigLoad(CONFIG_LOAD_FAILED))?
            .try_deserialize::<Self>()
            .map_err(|_| BrokerError::InvalidConfig(INVALID_BROKER_CONFIG))
    }

    pub fn cluster(&self) -> &ClusterConfig {
        &self.cluster
    }

    pub fn inter_broker(&self) -> &InterBrokerConfig {
        &self.inter_broker
    }
}

/// Current voter discovery progress for a running broker.
///
/// This is intentionally small for the bootstrap slice: later coordination work
/// will replace the initial local-only discovery with real inter-broker discovery.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DiscoveryState {
    Complete {
        discovered_voters: NonZeroUsize,
    },
    Discovering {
        discovered_voters: NonZeroUsize,
        required_voters: NonZeroUsize,
    },
}

impl DiscoveryState {
    pub fn discovered_voters(&self) -> NonZeroUsize {
        match self {
            Self::Complete { discovered_voters } | Self::Discovering { discovered_voters, .. } => *discovered_voters,
        }
    }

    pub fn is_complete(&self) -> bool {
        matches!(self, Self::Complete { .. })
    }
}

/// Write admission state exposed by broker startup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AdmissionState {
    AcceptingSingleNodeCluster,
    RejectingUntilCoordinationReady { reason: &'static str },
}

impl AdmissionState {
    pub fn admits_writes(&self) -> bool {
        matches!(self, Self::AcceptingSingleNodeCluster)
    }
}

/// Broker process before startup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Broker {
    local_node_id: BrokerNodeId,
    config: BrokerConfig,
}

impl Broker {
    pub fn new(config: BrokerConfig) -> Self {
        Self {
            local_node_id: BrokerNodeId::generate(),
            config,
        }
    }

    pub async fn start(self) -> Result<RunningBroker, BrokerError> {
        let expected_brokers = self.config.cluster().expected_brokers();
        let quorum_size = self.config.cluster().quorum_size();

        // Until real discovery exists, the broker can only prove its own voter.
        // Multi-node clusters must therefore reject writes to preserve admission safety.
        let discovered_voters = NonZeroUsize::MIN;

        let (discovery_state, admission_state) = if self.config.cluster().is_single_node() {
            info!(
                local_node_id = %self.local_node_id,
                expected_brokers = expected_brokers.get(),
                quorum = quorum_size.get(),
                "single-node cluster quorum is immediately available"
            );
            (
                DiscoveryState::Complete { discovered_voters },
                AdmissionState::AcceptingSingleNodeCluster,
            )
        } else {
            warn!(
                local_node_id = %self.local_node_id,
                expected_brokers = expected_brokers.get(),
                discovered_voters = discovered_voters.get(),
                quorum = quorum_size.get(),
                "multi-node cluster is waiting for dynamic voter discovery"
            );
            (
                DiscoveryState::Discovering {
                    discovered_voters,
                    required_voters: quorum_size,
                },
                AdmissionState::RejectingUntilCoordinationReady {
                    reason: COORDINATION_QUORUM_NOT_DISCOVERED,
                },
            )
        };

        Ok(RunningBroker {
            local_node_id: self.local_node_id,
            config: self.config,
            discovery_state,
            admission_state,
            topics: HashMap::new(),
        })
    }
}

#[derive(Debug, Clone, PartialEq)]
struct StoredMessage {
    timestamp_ns: TimestampNs,
    payload: MessagePayload,
}

#[derive(Debug, Clone, PartialEq)]
struct TopicLog {
    definition: TopicDefinition,
    messages: Vec<StoredMessage>,
}

/// Broker process after startup validation and initial discovery evaluation.
#[derive(Debug, Clone, PartialEq)]
pub struct RunningBroker {
    local_node_id: BrokerNodeId,
    config: BrokerConfig,
    discovery_state: DiscoveryState,
    admission_state: AdmissionState,
    topics: HashMap<TopicName, TopicLog>,
}

impl RunningBroker {
    pub fn local_node_id(&self) -> BrokerNodeId {
        self.local_node_id
    }

    pub fn config(&self) -> &BrokerConfig {
        &self.config
    }

    pub fn discovery_state(&self) -> &DiscoveryState {
        &self.discovery_state
    }

    pub fn admission_state(&self) -> &AdmissionState {
        &self.admission_state
    }

    pub fn declare_topic(&mut self, topic: TopicDefinition) -> Result<(), BrokerError> {
        let name = topic.name().clone();

        if self.topics.contains_key(&name) {
            return Err(BrokerError::TopicAlreadyExists(TOPIC_ALREADY_EXISTS));
        }

        self.topics.insert(
            name,
            TopicLog {
                definition: topic,
                messages: Vec::new(),
            },
        );

        Ok(())
    }

    pub fn publish(
        &mut self,
        topic: impl AsRef<str>,
        timestamp_ns: TimestampNs,
        payload: MessagePayload,
    ) -> Result<MessageNotification, BrokerError> {
        if !self.admission_state.admits_writes() {
            return Err(BrokerError::WriteAdmissionRejected(WRITE_ADMISSION_REJECTED));
        }

        let log = self
            .topics
            .get_mut(topic.as_ref())
            .ok_or(BrokerError::UnknownTopic(UNKNOWN_TOPIC))?;

        if payload.schema().as_ref() != log.definition.schema().as_ref() {
            return Err(BrokerError::PayloadSchemaMismatch(PAYLOAD_SCHEMA_MISMATCH));
        }

        if let Some(last_message) = log.messages.last() {
            if timestamp_ns <= last_message.timestamp_ns {
                return Err(BrokerError::MessageTimestampNotAdvancing(MESSAGE_TIMESTAMP_NOT_ADVANCING));
            }
        }

        let notification = MessageNotification::new(log.definition.name().clone(), timestamp_ns, payload.num_rows());
        log.messages.push(StoredMessage { timestamp_ns, payload });

        Ok(notification)
    }

    pub fn notifications_since(
        &self,
        topic: impl AsRef<str>,
        after_timestamp_ns: TimestampNs,
    ) -> Result<Vec<MessageNotification>, BrokerError> {
        let log = self.topics.get(topic.as_ref()).ok_or(BrokerError::UnknownTopic(UNKNOWN_TOPIC))?;

        Ok(log
            .messages
            .iter()
            .filter(|message| message.timestamp_ns > after_timestamp_ns)
            .map(|message| MessageNotification::new(log.definition.name().clone(), message.timestamp_ns, message.payload.num_rows()))
            .collect())
    }

    pub fn payloads_since(&self, topic: impl AsRef<str>, after_timestamp_ns: TimestampNs) -> Result<Vec<MessagePayload>, BrokerError> {
        let log = self.topics.get(topic.as_ref()).ok_or(BrokerError::UnknownTopic(UNKNOWN_TOPIC))?;

        Ok(log
            .messages
            .iter()
            .filter(|message| message.timestamp_ns > after_timestamp_ns)
            .map(|message| message.payload.clone())
            .collect())
    }
}

/// Broker startup/configuration errors.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum BrokerError {
    #[error("failed to load broker configuration: {0}")]
    ConfigLoad(&'static str),
    #[error("invalid broker configuration: {0}")]
    InvalidConfig(&'static str),
    #[error("message timestamp rejected: {0}")]
    MessageTimestampNotAdvancing(&'static str),
    #[error("payload rejected: {0}")]
    PayloadSchemaMismatch(&'static str),
    #[error("topic declaration rejected: {0}")]
    TopicAlreadyExists(&'static str),
    #[error("topic lookup failed: {0}")]
    UnknownTopic(&'static str),
    #[error("write rejected: {0}")]
    WriteAdmissionRejected(&'static str),
}
