use serde::Deserialize;
use std::{
    num::{NonZeroU16, NonZeroUsize},
    path::Path,
};
use thiserror::Error;
use tracing::{info, warn};
use uuid::Uuid;

pub const CONFIG_LOAD_FAILED: &str = "configuration file could not be loaded or deserialized";
pub const COORDINATION_QUORUM_NOT_DISCOVERED: &str = "cluster coordination has not discovered a voting quorum";
pub const INVALID_BROKER_NODE_UUID: &str = "broker node id must be a UUID";

/// Durable identity for a broker process.
///
/// IDs are generated by the broker instead of configured by operators so cluster
/// membership can be discovered and fenced by the coordination layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(transparent)]
pub struct BrokerNodeId(Uuid);

impl BrokerNodeId {
    pub fn generate() -> Self {
        Self(Uuid::new_v4())
    }

    pub fn new(value: Uuid) -> Self {
        Self(value)
    }

    pub fn parse(value: &str) -> Result<Self, BrokerError> {
        Uuid::parse_str(value)
            .map(Self)
            .map_err(|_| BrokerError::InvalidConfig(INVALID_BROKER_NODE_UUID))
    }

    pub fn as_uuid(&self) -> Uuid {
        self.0
    }
}

impl std::fmt::Display for BrokerNodeId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Operator-provided cluster size used to calculate quorum.
///
/// The configured count is deliberately separate from discovered membership:
/// every discovered broker is a voter, but writes are rejected until discovery
/// can prove that quorum is reachable.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct ClusterConfig {
    expected_brokers: NonZeroUsize,
}

impl ClusterConfig {
    pub fn new(expected_brokers: NonZeroUsize) -> Self {
        Self { expected_brokers }
    }

    pub fn single_node() -> Self {
        Self::new(NonZeroUsize::MIN)
    }

    pub fn expected_brokers(&self) -> NonZeroUsize {
        self.expected_brokers
    }

    pub fn quorum_size(&self) -> NonZeroUsize {
        NonZeroUsize::new((self.expected_brokers.get() / 2) + 1).expect("majority quorum for non-zero cluster size is non-zero")
    }

    pub fn is_single_node(&self) -> bool {
        self.expected_brokers.get() == 1
    }
}

/// Inter-broker communication settings.
///
/// Only the local port is configured. Peer addresses are discovered dynamically
/// by the cluster coordination path, not hardcoded in configuration.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct InterBrokerConfig {
    port: NonZeroU16,
}

impl InterBrokerConfig {
    pub fn new(port: NonZeroU16) -> Self {
        Self { port }
    }

    pub fn port(&self) -> NonZeroU16 {
        self.port
    }
}

/// Static broker startup configuration loaded from TOML, JSON, or YAML.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct BrokerConfig {
    cluster: ClusterConfig,
    inter_broker: InterBrokerConfig,
}

impl BrokerConfig {
    pub fn new(cluster: ClusterConfig, inter_broker: InterBrokerConfig) -> Self {
        Self { cluster, inter_broker }
    }

    pub fn single_node(port: NonZeroU16) -> Self {
        Self::new(ClusterConfig::single_node(), InterBrokerConfig::new(port))
    }

    pub fn from_path(path: impl AsRef<Path>) -> Result<Self, BrokerError> {
        config::Config::builder()
            .add_source(config::File::from(path.as_ref()))
            .build()
            .map_err(|_| BrokerError::ConfigLoad(CONFIG_LOAD_FAILED))?
            .try_deserialize::<Self>()
            .map_err(|_| BrokerError::ConfigLoad(CONFIG_LOAD_FAILED))
    }

    pub fn cluster(&self) -> &ClusterConfig {
        &self.cluster
    }

    pub fn inter_broker(&self) -> &InterBrokerConfig {
        &self.inter_broker
    }
}

/// Current voter discovery progress for a running broker.
///
/// This is intentionally small for the bootstrap slice: later coordination work
/// will replace the initial local-only discovery with real inter-broker discovery.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DiscoveryState {
    Complete {
        discovered_voters: NonZeroUsize,
    },
    Discovering {
        discovered_voters: NonZeroUsize,
        required_voters: NonZeroUsize,
    },
}

impl DiscoveryState {
    pub fn discovered_voters(&self) -> NonZeroUsize {
        match self {
            Self::Complete { discovered_voters } | Self::Discovering { discovered_voters, .. } => *discovered_voters,
        }
    }

    pub fn is_complete(&self) -> bool {
        matches!(self, Self::Complete { .. })
    }
}

/// Write admission state exposed by broker startup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AdmissionState {
    AcceptingSingleNodeCluster,
    RejectingUntilCoordinationReady { reason: &'static str },
}

impl AdmissionState {
    pub fn admits_writes(&self) -> bool {
        matches!(self, Self::AcceptingSingleNodeCluster)
    }
}

/// Broker process before startup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Broker {
    local_node_id: BrokerNodeId,
    config: BrokerConfig,
}

impl Broker {
    pub fn new(config: BrokerConfig) -> Self {
        Self {
            local_node_id: BrokerNodeId::generate(),
            config,
        }
    }

    pub fn start(self) -> RunningBroker {
        let expected_brokers = self.config.cluster().expected_brokers();
        let quorum_size = self.config.cluster().quorum_size();

        // Until real discovery exists, the broker can only prove its own voter.
        // Multi-node clusters must therefore reject writes to preserve admission safety.
        let discovered_voters = NonZeroUsize::MIN;

        let (discovery_state, admission_state) = if self.config.cluster().is_single_node() {
            info!(
                local_node_id = %self.local_node_id,
                expected_brokers = expected_brokers.get(),
                quorum = quorum_size.get(),
                "single-node cluster quorum is immediately available"
            );
            (
                DiscoveryState::Complete { discovered_voters },
                AdmissionState::AcceptingSingleNodeCluster,
            )
        } else {
            warn!(
                local_node_id = %self.local_node_id,
                expected_brokers = expected_brokers.get(),
                discovered_voters = discovered_voters.get(),
                quorum = quorum_size.get(),
                "multi-node cluster is waiting for dynamic voter discovery"
            );
            (
                DiscoveryState::Discovering {
                    discovered_voters,
                    required_voters: quorum_size,
                },
                AdmissionState::RejectingUntilCoordinationReady {
                    reason: COORDINATION_QUORUM_NOT_DISCOVERED,
                },
            )
        };

        RunningBroker {
            local_node_id: self.local_node_id,
            config: self.config,
            discovery_state,
            admission_state,
        }
    }
}

/// Broker process after startup validation and initial discovery evaluation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RunningBroker {
    local_node_id: BrokerNodeId,
    config: BrokerConfig,
    discovery_state: DiscoveryState,
    admission_state: AdmissionState,
}

impl RunningBroker {
    pub fn local_node_id(&self) -> BrokerNodeId {
        self.local_node_id
    }

    pub fn config(&self) -> &BrokerConfig {
        &self.config
    }

    pub fn discovery_state(&self) -> &DiscoveryState {
        &self.discovery_state
    }

    pub fn admission_state(&self) -> &AdmissionState {
        &self.admission_state
    }
}

/// Broker startup/configuration errors.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum BrokerError {
    #[error("failed to load broker configuration: {0}")]
    ConfigLoad(&'static str),
    #[error("invalid broker configuration: {0}")]
    InvalidConfig(&'static str),
}
